(() => {
  'use strict';
  const CONFIG_KEY='hector_rotina_config_v3', STATE_KEY='hector_rotina_state_v3';
  const SUPABASE_URL='https://aictkwkcyqjsakugiwra.supabase.co', SUPABASE_PUBLISHABLE_KEY='sb_publishable_BJUaEs1EMKYDfCkg_6wnYA_7sWmgXWT';
  const ROUTINE_ID='077cb586-35c1-49a8-b864-8d2d88f1010f';
  const LEGACY_APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbz0RETrtzuA3pwdXu3qB2PN611q3PRY0Tw8CUyF7AyashsCKTm3yZ93s7iGtDe8m35p/exec';
  const memory=Object.create(null), DOW_TO_PT=['dom','seg','ter','qua','qui','sex','sab'];
  const PET_STAGES=[{key:'ovo',label:'Ovo intacto'},{key:'ovo1',label:'Primeira rachadura'},{key:'ovo2',label:'Rachadura inicial'},{key:'ovo3',label:'Rachando'},{key:'ovo4',label:'Mais rachaduras'},{key:'ovo5',label:'Casca cedendo'},{key:'ovo6',label:'Quase abrindo'},{key:'ovo7',label:'Casca bem rachada'},{key:'ovo8',label:'Pronto para nascer'},{key:'hatch1',label:'Começando a eclodir'},{key:'hatch2',label:'Cabeça aparecendo'},{key:'hatch3',label:'Saindo da casca'},{key:'hatch4',label:'Recém-nascido'},{key:'hatch5',label:'Primeiros movimentos'},{key:'baby1',label:'Bebê Pacus'},{key:'baby2',label:'Bebê crescendo'},{key:'baby3',label:'Filhote'},{key:'baby4',label:'Filhote forte'},{key:'baby5',label:'Jovem'},{key:'young1',label:'Jovem crescendo'},{key:'young2',label:'Quase adulto'},{key:'young3',label:'Quase pronto'},{key:'young4',label:'Última fase'},{key:'adulto',label:'Pacus adulto'}];
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(_){return v;}}
  function readJSON(k,f=null){return Object.prototype.hasOwnProperty.call(memory,k)?clone(memory[k]):f;}
  function writeJSON(k,v){memory[k]=clone(v);return true;}
  function remove(k){delete memory[k];return true;}
  function todayISO(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());}
  function hhmm(v){return v?String(v).slice(0,5):null;}
  async function request(path,options={}){const h=new Headers(options.headers||{});h.set('apikey',SUPABASE_PUBLISHABLE_KEY);h.set('Authorization',`Bearer ${SUPABASE_PUBLISHABLE_KEY}`);h.set('Content-Type','application/json');h.set('Accept','application/json');const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...options,headers:h,cache:'no-store'}),t=await r.text();let b=null;try{b=t?JSON.parse(t):null;}catch(_){b=t;}if(!r.ok){const e=new Error(b?.message||b?.error_description||b?.hint||b?.details||`Supabase HTTP ${r.status}`);e.status=r.status;e.body=b;throw e;}return b;}
  function rpc(name,payload){return request(`rpc/${name}`,{method:'POST',body:JSON.stringify(payload||{})});}
  async function loadConfig(){const [periods,tasks,rewards,settingsRows,petRows,schedule,exceptions]=await Promise.all([request(`routine_periods?routine_id=eq.${ROUTINE_ID}&order=position.asc`),request(`tasks?active=eq.true&order=position.asc&select=*,routine_periods!inner(routine_id,key)&routine_periods.routine_id=eq.${ROUTINE_ID}`),request(`rewards?routine_id=eq.${ROUTINE_ID}&active=eq.true&order=position.asc`),request(`routine_settings?routine_id=eq.${ROUTINE_ID}&limit=1`),request(`pet_state?routine_id=eq.${ROUTINE_ID}&limit=1`),request(`recurring_schedule?routine_id=eq.${ROUTINE_ID}&active=eq.true`),request(`schedule_exceptions?routine_id=eq.${ROUTINE_ID}`)]);const periodsByKey={};(periods||[]).filter(p=>p.key!=='outros').forEach(p=>periodsByKey[p.key]={label:p.label,time:`${hhmm(p.start_time)} – ${hhmm(p.end_time)}`,tasks:[]});(tasks||[]).forEach(t=>{const key=t.routine_periods?.key;if(!key||!periodsByKey[key])return;const e={id:t.id,txt:t.title,pts:t.points};if(t.subtitle)e.sub=t.subtitle;if(t.tier)e.tier=t.tier;if(t.external)e.external=true;if(t.full_penalty)e.fullPenalty=true;periodsByKey[key].tasks.push(e);});const settings=settingsRows?.[0]||{},pet=petRows?.[0]||{};return {periods:periodsByKey,periodsWeekend:null,badHabits:[],rewards:(rewards||[]).map(r=>{const e={id:r.id,txt:r.title,cost:r.cost};if(r.grants_hours!=null)e.grantsHours=Number(r.grants_hours);if(r.max_per_day!=null)e.maxPerDay=r.max_per_day;return e;}),screenDailyLimitHours:settings.screen_daily_limit_hours??2,perfectDayBonusMinutes:settings.perfect_day_bonus_minutes??30,historyStartDate:settings.history_start_date||null,schedule:(schedule||[]).map(s=>({id:s.id,label:s.label,days:(s.days_of_week||[]).map(n=>DOW_TO_PT[n]).filter(Boolean),start:hhmm(s.start_time),end:hhmm(s.end_time),period:s.period_key,pts:s.points})),scheduleExceptions:(exceptions||[]).map(e=>({id:e.id,date:e.date,label:e.label,period:e.period_key,pts:e.points,start:hhmm(e.start_time),end:hhmm(e.end_time)})),pet:{name:pet.name||'Pacus',growthStartDate:pet.growth_start_date||null,growthEndDate:pet.growth_end_date||null,stages:PET_STAGES}};}
  function normalizeRuntimeState(runtime){if(!runtime||typeof runtime!=='object')throw new Error('invalid_runtime_state');const dailyRun=runtime.dailyRun||{},checkedToday={},ui=runtime.uiState||{},gt=ui.gameTimer||{};(runtime.completions||[]).forEach(c=>{if(c?.task_id)checkedToday[c.task_id]=c.status;});const history={};Object.entries(runtime.history||{}).forEach(([date,item])=>{const done=Number(item?.done??0),total=Number(item?.total??0),points=Number(item?.pointsEarnedThatDay??0);history[date]={...item,done,total,doneCount:done,taskCount:total,pointsEarnedThatDay:points,points,perfect:!!item?.perfect};});const date=runtime.date||dailyRun.date||todayISO();return {lastDate:date,checkedToday,customTaskOrder:{},totalPoints:Number(runtime.balance??0),log:[],history,hairByDate:{},petCompletedDays:Array.isArray(ui.petCompletedDays)?ui.petCompletedDays:[],petPerfectBonusDays:Array.isArray(ui.petPerfectBonusDays)?ui.petPerfectBonusDays:[],lastSeenPetStage:Number(ui.lastSeenPetStage??0),petLastCompletionISO:ui.petLastCompletionISO||null,petMaxDaysEquivalentEverSeen:0,gameTimer:{date:gt.date||date,usedSeconds:Number(gt.usedSeconds??0),runningSince:gt.runningSince||null,bonusSeconds:Number(gt.bonusSeconds??0),redemptions:gt.redemptions&&typeof gt.redemptions==='object'?gt.redemptions:{}},lifetimeRedemptions:{},dailyRun:{id:dailyRun.id||null,date,status:dailyRun.status||'open',doneCount:Number(dailyRun.done_count??0),taskCount:Number(dailyRun.task_count??0),points:Number(dailyRun.points_earned??0),perfect:!!dailyRun.perfect}};}
  async function loadState(){return normalizeRuntimeState(await rpc('child_get_runtime_state',{p_routine_id:ROUTINE_ID}));}
  async function getRemote(){const [config,state]=await Promise.all([loadConfig(),loadState()]);writeJSON(CONFIG_KEY,config);writeJSON(STATE_KEY,state);return {config,state,revision:0,serverUpdatedAt:new Date().toISOString(),domains:{routineConfig:config,dailyState:state,pointEvents:[],history:state.history||{}}};}
  async function markTask(taskId,status){const runtime=await rpc('child_mark_task',{p_routine_id:ROUTINE_ID,p_task_id:taskId,p_status:status||'pending'});const state=normalizeRuntimeState(runtime);writeJSON(STATE_KEY,state);return {...runtime,state,status:runtime.status??(status||null),pointsAwarded:Number(runtime.pointsAwarded??0),action:runtime.action||null};}
  function extractUiState(snapshot){const s=snapshot?.state||snapshot||readJSON(STATE_KEY,{})||{};const g=s.gameTimer||{};return {lastDate:s.lastDate||g.date||todayISO(),gameTimer:{date:g.date||s.lastDate||todayISO(),usedSeconds:Math.max(0,Number(g.usedSeconds)||0),runningSince:g.runningSince||null,bonusSeconds:Math.max(0,Number(g.bonusSeconds)||0),redemptions:g.redemptions&&typeof g.redemptions==='object'?g.redemptions:{}},lastSeenPetStage:Math.max(0,Number(s.lastSeenPetStage)||0),petCompletedDays:Array.isArray(s.petCompletedDays)?s.petCompletedDays:[],petPerfectBonusDays:Array.isArray(s.petPerfectBonusDays)?s.petPerfectBonusDays:[],petLastCompletionISO:s.petLastCompletionISO||null};}
  async function saveRemote(snapshot){const ui=extractUiState(snapshot);const result=await rpc('save_child_ui_state',{p_routine_id:ROUTINE_ID,p_state:ui});const current=readJSON(STATE_KEY,{});writeJSON(STATE_KEY,{...current,...ui,gameTimer:ui.gameTimer});return {ok:true,revision:0,serverUpdatedAt:new Date().toISOString(),result};}
  async function replaceRemote(snapshot){if(!snapshot||typeof snapshot!=='object'||!snapshot.state)throw new Error('Backup inválido');return saveRemote(snapshot);}
  const nativeFetch=window.fetch.bind(window);window.fetch=async function(input,init={}){const url=typeof input==='string'?input:input?.url||'';if(!url.startsWith(LEGACY_APPS_SCRIPT_URL))return nativeFetch(input,init);try{const method=(init.method||(typeof input!=='string'&&input?.method)||'GET').toUpperCase();if(method==='GET'){const remote=await getRemote();return new Response(JSON.stringify({ok:true,...remote}),{status:200,headers:{'Content-Type':'application/json'}});}let snapshot=null;try{snapshot=init.body?JSON.parse(init.body):null;}catch(_){}return new Response(JSON.stringify(await saveRemote(snapshot)),{status:200,headers:{'Content-Type':'application/json'}});}catch(error){return new Response(JSON.stringify(error?.result||{ok:false,error:error?.message||'storage_error'}),{status:200,headers:{'Content-Type':'application/json'}});}};
  window.RotinaStorage=Object.freeze({CONFIG_KEY,STATE_KEY,APPS_SCRIPT_URL:'',DATA_ENDPOINT:'',SUPABASE_URL,ROUTINE_ID,readJSON,writeJSON,remove,getRemote,saveRemote,replaceRemote,markTask,loadState,normalizeRuntimeState});
  const realBrowserStorage=window.localStorage;const sessionOnlyStorage=Object.freeze({getItem(k){const v=readJSON(k,null);if(v!=null)return JSON.stringify(v);try{return realBrowserStorage.getItem(k);}catch(_){return null;}},setItem(k,v){try{memory[k]=JSON.parse(v);}catch(_){memory[k]=v;}try{realBrowserStorage.setItem(k,v);}catch(_){}},removeItem(k){remove(k);try{realBrowserStorage.removeItem(k);}catch(_){}},clear(){Object.keys(memory).forEach(k=>delete memory[k]);try{realBrowserStorage.clear();}catch(_){}},key(i){return Object.keys(memory)[i]??null;},get length(){return Object.keys(memory).length;}});window.__ROTINA_SESSION_STORAGE__=sessionOnlyStorage;
})();
const localStorage=window.__ROTINA_SESSION_STORAGE__;