const DATA_FILE = 'rotina-backup.json';
const BACKUP_PREFIX = 'rotina-backup-';
const MAX_DAILY_BACKUPS = 30;
const TIMEZONE = 'America/Sao_Paulo';
function jsonResponse(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON);}
function findDataFile(){const current=DriveApp.getFilesByName(DATA_FILE);if(current.hasNext())return current.next();const files=DriveApp.getFiles();const legacyPattern=/^rotina-(?!.*\d{4}-\d{2}-\d{2}\.json$).*backup\.json$/;while(files.hasNext()){const file=files.next();if(legacyPattern.test(file.getName())){file.setName(DATA_FILE);return file;}}return DriveApp.createFile(DATA_FILE,'{}',MimeType.PLAIN_TEXT);}
function readJson(file){try{return JSON.parse(file.getBlob().getDataAsString()||'{}');}catch(err){return {};}}
function isoDate(date){return Utilities.formatDate(date||new Date(),TIMEZONE,'yyyy-MM-dd');}
function isoDateOffset(days){const d=new Date();d.setDate(d.getDate()+days);return isoDate(d);}
function localHourMinute(){return Utilities.formatDate(new Date(),TIMEZONE,'HH:mm');}

/* DATA MODEL V2: configuração, estado diário, ledger de pontos e histórico. */
function emptyModel(){return{schemaVersion:2,routineConfig:{},dailyState:{},pointEvents:[],history:{},revision:0,serverUpdatedAt:null};}
function isV2(data){return data&&Number(data.schemaVersion)>=2&&data.routineConfig&&data.dailyState&&data.history;}
function modelFromLegacy(legacy){
  if(isV2(legacy))return legacy;
  const state=legacy&&legacy.state?legacy.state:{};const config=legacy&&legacy.config?legacy.config:{};
  return{schemaVersion:2,routineConfig:config,dailyState:Object.assign({},state,{history:undefined,pointEvents:undefined}),pointEvents:Array.isArray(state.pointEvents)?state.pointEvents:[],history:state.history||{},revision:Number(legacy&&legacy.revision||state.driveRevision||0),serverUpdatedAt:legacy&&legacy.serverUpdatedAt||null};
}
function modelFromIncoming(incoming,current){
  const d=incoming&&incoming.domains?incoming.domains:{};
  if(d.routineConfig||d.dailyState||d.history||d.pointEvents){
    return{schemaVersion:2,routineConfig:d.routineConfig||{},dailyState:d.dailyState||{},pointEvents:Array.isArray(d.pointEvents)?d.pointEvents:[],history:d.history||{},revision:Number(current.revision||0),serverUpdatedAt:null};
  }
  return modelFromLegacy(incoming||current);
}
function legacyFromModel(model){const daily=Object.assign({},model.dailyState||{});daily.history=model.history||{};daily.pointEvents=model.pointEvents||[];daily.driveRevision=Number(model.revision||daily.driveRevision||0);return{ok:true,schemaVersion:2,revision:Number(model.revision||0),config:model.routineConfig||{},state:daily,serverUpdatedAt:model.serverUpdatedAt||null,domains:{routineConfig:model.routineConfig||{},dailyState:model.dailyState||{},pointEvents:model.pointEvents||[],history:model.history||{}}};}
function appendPointEventsFromState(model,oldState,newState){const oldTotal=Number(oldState&&oldState.totalPoints||0),newTotal=Number(newState&&newState.totalPoints||0),delta=newTotal-oldTotal;if(!delta)return;model.pointEvents=Array.isArray(model.pointEvents)?model.pointEvents:[];model.pointEvents.push({id:Utilities.getUuid(),type:'state_reconciliation',amount:delta,balanceAfter:newTotal,date:isoDate(new Date()),createdAt:new Date().toISOString()});}
function persistModel(file,model,oldState){model.schemaVersion=2;model.revision=Number(model.revision||0);model.serverUpdatedAt=new Date().toISOString();if(oldState)appendPointEventsFromState(model,oldState,model.dailyState||{});file.setContent(JSON.stringify(model,null,2));}
function doGet(){const file=findDataFile(),raw=readJson(file),model=modelFromLegacy(raw);if(!isV2(raw)){model.revision=Number(raw.revision||0);model.serverUpdatedAt=raw.serverUpdatedAt||null;file.setContent(JSON.stringify(model,null,2));}return jsonResponse(legacyFromModel(model));}
function doPost(e){let incoming;try{incoming=JSON.parse((e.postData&&e.postData.contents)||'{}');}catch(err){return jsonResponse({ok:false,error:'invalid_json'});}const lock=LockService.getScriptLock();try{lock.waitLock(10000);const file=findDataFile(),current=modelFromLegacy(readJson(file)),currentRevision=Number(current.revision||0),baseRevision=Number(incoming.baseRevision||0);if(currentRevision>0&&baseRevision!==currentRevision)return jsonResponse({ok:false,conflict:true,revision:currentRevision,data:legacyFromModel(current)});const next=modelFromIncoming(incoming,current);next.routineConfig=incoming.domains?.routineConfig||incoming.config||next.routineConfig||{};next.dailyState=incoming.domains?.dailyState||incoming.state||next.dailyState||{};next.history=incoming.domains?.history||(incoming.state&&incoming.state.history)||next.history||{};next.pointEvents=Array.isArray(incoming.domains?.pointEvents)?incoming.domains.pointEvents:Array.isArray(incoming.pointEvents)?incoming.pointEvents:next.pointEvents||[];next.revision=currentRevision+1;next.dailyState.driveRevision=next.revision;persistModel(file,next,current.dailyState||{});createDailyBackup(next);pruneDailyBackups();return jsonResponse({ok:true,revision:next.revision,serverUpdatedAt:next.serverUpdatedAt});}catch(err){if(String(err&&err.message||err).indexOf('Lock')!==-1)return jsonResponse({ok:false,error:'lock_timeout'});return jsonResponse({ok:false,error:'server_error'});}finally{try{lock.releaseLock();}catch(ignore){}}}
function setupDailyCloseTrigger(){ScriptApp.getProjectTriggers().filter(t=>t.getHandlerFunction()==='checkDailyClose').forEach(t=>ScriptApp.deleteTrigger(t));ScriptApp.newTrigger('checkDailyClose').timeBased().everyMinutes(1).create();}
function removeDailyCloseTrigger(){ScriptApp.getProjectTriggers().filter(t=>t.getHandlerFunction()==='checkDailyClose').forEach(t=>ScriptApp.deleteTrigger(t));}
function checkDailyClose(){const hm=localHourMinute();if(hm>='23:59')return closeRoutineDay(isoDate(new Date()));if(hm<='00:10')return closeRoutineDay(isoDateOffset(-1));}
function tasksForDate(config,dateISO){if(!config)return[];const d=new Date(dateISO+'T12:00:00'),weekend=d.getDay()===0||d.getDay()===6,source=weekend&&config.periodsWeekend?config.periodsWeekend:config.periods;if(!source)return[];const result=[];['manha','tarde','noite'].forEach(period=>{const tasks=Array.isArray(source[period]&&source[period].tasks)?source[period].tasks:[];tasks.forEach(task=>{if(task&&task.id)result.push(task);});});return result;}
function taskPoints(tasks){return tasks.reduce((sum,task)=>sum+Number(task&&task.pts||0),0);}
function closeRoutineDay(dateISO){const lock=LockService.getScriptLock();try{lock.waitLock(10000);const file=findDataFile(),model=modelFromLegacy(readJson(file)),state=model.dailyState||{},config=model.routineConfig||{};model.history=model.history||{};state.autoClosedDates=state.autoClosedDates||{};if(state.autoClosedDates[dateISO])return;const tasks=tasksForDate(config,dateISO),previous=model.history[dateISO]||{},checkedToday=state.checkedToday||{},checkedTasks=tasks.filter(task=>checkedToday[task.id]===true||checkedToday[task.id]==='done'||checkedToday[task.id]==='help'),total=tasks.length||Number(previous.total||0),previousDone=Number(previous.done||0),done=checkedTasks.length>0?checkedTasks.length:Math.min(previousDone,total),pointsEarnedThatDay=checkedTasks.length>0?taskPoints(checkedTasks):Number(previous.pointsEarnedThatDay||0),perfect=total>0&&done===total;model.history[dateISO]=Object.assign({},previous,{done,total,pointsEarnedThatDay,perfect,screenMinutes:perfect?Number(config.perfectDayBonusMinutes||30):Number(previous.screenMinutes||0),autoClosedAt:new Date().toISOString()});state.autoClosedDates[dateISO]=true;state.lastAutoClosedDate=dateISO;model.dailyState=state;model.revision=Number(model.revision||0)+1;state.driveRevision=model.revision;persistModel(file,model);createDailyBackup(model);pruneDailyBackups();}finally{try{lock.releaseLock();}catch(ignore){}}}
function repairLegacyHistory(){const lock=LockService.getScriptLock();try{lock.waitLock(10000);const file=findDataFile(),model=modelFromLegacy(readJson(file)),config=model.routineConfig||{},history=model.history||{};let changed=false;Object.keys(history).forEach(dateISO=>{const item=history[dateISO]||{},done=Number(item.done||0),total=Number(item.total||0);if(!item.perfect||done!==1||total!==1)return;const tasks=tasksForDate(config,dateISO);if(!tasks.length)return;item.done=tasks.length;item.total=tasks.length;item.pointsEarnedThatDay=taskPoints(tasks);item.perfect=true;item.legacyHistoryNormalizedAt=new Date().toISOString();history[dateISO]=item;changed=true;});if(!changed)return{ok:true,changed:false};model.history=history;model.revision=Number(model.revision||0)+1;model.dailyState.driveRevision=model.revision;persistModel(file,model);createDailyBackup(model);pruneDailyBackups();return{ok:true,changed:true,revision:model.revision};}finally{try{lock.releaseLock();}catch(ignore){}}}
function createDailyBackup(data){const date=Utilities.formatDate(new Date(),TIMEZONE,'yyyy-MM-dd'),name=BACKUP_PREFIX+date+'.json',backups=DriveApp.getFilesByName(name);if(!backups.hasNext())DriveApp.createFile(name,JSON.stringify(data,null,2),MimeType.PLAIN_TEXT);}
function pruneDailyBackups(){const allBackups=[],files=DriveApp.getFiles();while(files.hasNext()){const file=files.next();if(/^rotina-backup-\d{4}-\d{2}-\d{2}\.json$/.test(file.getName()))allBackups.push(file);}allBackups.sort((a,b)=>b.getDateCreated().getTime()-a.getDateCreated().getTime());for(let i=MAX_DAILY_BACKUPS;i<allBackups.length;i++)allBackups[i].setTrashed(true);}
